### ISSUE TITLE
Error: Failed loading extension

### ISSUE THREAD

**Issue by ebdavison** [sprin/markdown-inline-graphviz#6]
I have installed mkdocs, inline_graphviz and graphviz.  One of my systems works properly and generates the inline SVG.  However, on two other systems with same installed packages, I get the following error:

```
$ mkdocs build
ERROR   -  Config value: 'markdown_extensions'. Error: Failed loading extension "inline_graphviz".

Aborted with 1 Configuration Errors!
```
Here is the mkdocs.yml file:

```
markdown_extensions:
    - inline_graphviz
site_name: relay01
nav:
    - Home: index.md
    - Files: files.md

```
